
import com.placeholder.PlaceHolder;
import com.sun.corba.se.impl.orbutil.ORBUtility;
import java.awt.Button;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.Period;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Mosin
 */
public class frmDashboard extends javax.swing.JFrame {

    /**
     * Creates new form frmDashboard
     */
    DBConn c = new DBConn();
    String gen = null;
    String user_email;

    PlaceHolder p;

    public frmDashboard(String email) {
        user_email = email;
        initComponents();
        pnlAddContact.hide();
        pnlUpdateContact.hide();
        DeleteContact.hide();
        ViewContact.hide();
        getContact();
        System.out.println(user_email);
        
        
      
    }
   
    public static  boolean validation(String txt){
        String regx = "^[a-zA-Z]+\\.?";
        Pattern pattern = Pattern.compile(regx,Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(txt);
        return matcher.find();
    }
    
    public static  boolean addressvalidation(String txt){
        String regx = "^[a-zA-Z0-9]+\\.?";
        Pattern pattern = Pattern.compile(regx,Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(txt);
        return matcher.find();
    }

    public void getContact() {

        try {

            c.select("SELECT `Phone-No`,`Name` FROM `addcontact` WHERE `user_email`='" + user_email + "'");
            while (c.rs.next()) {
//                cmbVContact.addItem(c.rs.getString("Phone-No"));
                cmbDname.addItem(c.rs.getString("Name"));
                cmbUname.addItem(c.rs.getString("Name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void hidePanel() {

        pnlAddContact.hide();
        pnlUpdateContact.hide();
        DeleteContact.hide();
        ViewContact.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        pnlAddContact = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtphoneno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtemailid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtzipcode = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtstate = new javax.swing.JTextField();
        cmbdate = new javax.swing.JComboBox<>();
        cmbmonth = new javax.swing.JComboBox<>();
        cmbyears = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtfemale = new javax.swing.JRadioButton();
        txtmale = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        cmbGroup = new javax.swing.JComboBox<>();
        pnlUpdateContact = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        cmbUname = new javax.swing.JComboBox<>();
        txtUaddress = new javax.swing.JTextField();
        txtUphone = new javax.swing.JTextField();
        txtUage = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtUemailid = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtUzipcode = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtUstate = new javax.swing.JTextField();
        cmbudate = new javax.swing.JComboBox<>();
        cmbumonth = new javax.swing.JComboBox<>();
        cmbuyear = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton7 = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        DeleteContact = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        txtDphone = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        btncancel = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        cmbDname = new javax.swing.JComboBox<>();
        ViewContact = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtVaddress = new javax.swing.JTextField();
        txtVphone = new javax.swing.JTextField();
        txtVage = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtvemailid = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtVzipcode = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtVstate = new javax.swing.JTextField();
        cmbvdate = new javax.swing.JComboBox<>();
        cmbvmonth = new javax.swing.JComboBox<>();
        cmbvyear = new javax.swing.JComboBox<>();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        rdvfemale = new javax.swing.JRadioButton();
        rdVmale = new javax.swing.JRadioButton();
        btnCancel = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        cmbsearch = new javax.swing.JComboBox<>();
        txtVName1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMame = new javax.swing.JTable();
        pnlmenubaar = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        txtlogout = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        pnlAddContact.setBackground(new java.awt.Color(255, 153, 153));
        pnlAddContact.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlAddContact.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD THE CONTACT");
        pnlAddContact.add(jLabel1);
        jLabel1.setBounds(240, 10, 350, 40);

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter The Email-ID :");
        pnlAddContact.add(jLabel2);
        jLabel2.setBounds(430, 180, 180, 20);

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enter The Name :");
        pnlAddContact.add(jLabel3);
        jLabel3.setBounds(100, 100, 170, 20);

        txtAddress.setBackground(new java.awt.Color(255, 153, 153));
        txtAddress.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        pnlAddContact.add(txtAddress);
        txtAddress.setBounds(140, 210, 240, 30);

        txtname.setBackground(new java.awt.Color(255, 153, 153));
        txtname.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        pnlAddContact.add(txtname);
        txtname.setBounds(140, 130, 240, 30);

        txtage.setBackground(new java.awt.Color(255, 153, 153));
        txtage.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtage.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtageActionPerformed(evt);
            }
        });
        pnlAddContact.add(txtage);
        txtage.setBounds(530, 370, 60, 30);

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Age :");
        pnlAddContact.add(jLabel5);
        jLabel5.setBounds(440, 370, 100, 30);

        txtphoneno.setBackground(new java.awt.Color(255, 153, 153));
        txtphoneno.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtphoneno.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtphoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphonenoActionPerformed(evt);
            }
        });
        pnlAddContact.add(txtphoneno);
        txtphoneno.setBounds(490, 130, 240, 30);

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Enter The Phone-No :");
        pnlAddContact.add(jLabel4);
        jLabel4.setBounds(430, 100, 177, 20);

        txtemailid.setBackground(new java.awt.Color(255, 153, 153));
        txtemailid.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtemailid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtemailid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailidActionPerformed(evt);
            }
        });
        pnlAddContact.add(txtemailid);
        txtemailid.setBounds(490, 210, 240, 30);

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Enter The  permanent Address :");
        pnlAddContact.add(jLabel6);
        jLabel6.setBounds(100, 180, 270, 21);

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Enter The Pin Code :");
        pnlAddContact.add(jLabel7);
        jLabel7.setBounds(100, 340, 200, 21);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ADD CONTACT");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(230, 20, 290, 40);

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Enter The Email-ID");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(440, 180, 170, 20);

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Enter The Name");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(100, 100, 132, 20);

        jTextField6.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField6);
        jTextField6.setBounds(120, 210, 220, 27);

        jTextField7.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField7);
        jTextField7.setBounds(120, 130, 220, 27);

        jTextField8.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField8);
        jTextField8.setBounds(110, 310, 220, 27);

        jLabel11.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Enter The Phone-No");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(450, 100, 170, 20);

        jLabel12.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Birth of Date");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(440, 270, 170, 21);

        jTextField9.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField9);
        jTextField9.setBounds(470, 130, 220, 27);

        jTextField10.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField10);
        jTextField10.setBounds(470, 210, 220, 27);

        jLabel13.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Enter The Address");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(90, 180, 170, 21);

        jLabel14.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Enter The State");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(100, 270, 170, 21);

        pnlAddContact.add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);

        txtzipcode.setBackground(new java.awt.Color(255, 153, 153));
        txtzipcode.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtzipcode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtzipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtzipcodeActionPerformed(evt);
            }
        });
        pnlAddContact.add(txtzipcode);
        txtzipcode.setBounds(210, 370, 100, 30);

        jLabel15.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Enter The State :");
        pnlAddContact.add(jLabel15);
        jLabel15.setBounds(100, 260, 170, 21);

        txtstate.setBackground(new java.awt.Color(255, 153, 153));
        txtstate.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtstate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstateActionPerformed(evt);
            }
        });
        pnlAddContact.add(txtstate);
        txtstate.setBounds(140, 290, 240, 30);

        cmbdate.setBackground(new java.awt.Color(255, 153, 153));
        cmbdate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cmbdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbdateActionPerformed(evt);
            }
        });
        pnlAddContact.add(cmbdate);
        cmbdate.setBounds(480, 300, 60, 30);

        cmbmonth.setBackground(new java.awt.Color(255, 153, 153));
        cmbmonth.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        pnlAddContact.add(cmbmonth);
        cmbmonth.setBounds(550, 300, 60, 30);

        cmbyears.setBackground(new java.awt.Color(255, 153, 153));
        cmbyears.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbyears.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", " " }));
        cmbyears.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbyearsItemStateChanged(evt);
            }
        });
        cmbyears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbyearsActionPerformed(evt);
            }
        });
        pnlAddContact.add(cmbyears);
        cmbyears.setBounds(620, 300, 80, 30);

        jLabel31.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText(" Date Of Birth  :");
        pnlAddContact.add(jLabel31);
        jLabel31.setBounds(430, 260, 130, 30);

        jLabel32.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Select The Gender :");
        pnlAddContact.add(jLabel32);
        jLabel32.setBounds(100, 420, 190, 20);

        txtfemale.setBackground(new java.awt.Color(255, 153, 153));
        buttonGroup1.add(txtfemale);
        txtfemale.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtfemale.setText("Female");
        txtfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfemaleActionPerformed(evt);
            }
        });
        pnlAddContact.add(txtfemale);
        txtfemale.setBounds(260, 450, 93, 30);

        txtmale.setBackground(new java.awt.Color(255, 153, 153));
        buttonGroup1.add(txtmale);
        txtmale.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtmale.setText("Male");
        txtmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaleActionPerformed(evt);
            }
        });
        pnlAddContact.add(txtmale);
        txtmale.setBounds(160, 450, 65, 29);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlAddContact.add(jButton1);
        jButton1.setBounds(430, 520, 120, 30);

        btnadd.setBackground(new java.awt.Color(0, 0, 0));
        btnadd.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        pnlAddContact.add(btnadd);
        btnadd.setBounds(290, 520, 77, 30);

        cmbGroup.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select The Group", "Family", "Friends", "Workers", "Office", "Others" }));
        cmbGroup.setToolTipText("");
        cmbGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGroupActionPerformed(evt);
            }
        });
        pnlAddContact.add(cmbGroup);
        cmbGroup.setBounds(310, 50, 170, 30);

        getContentPane().add(pnlAddContact);
        pnlAddContact.setBounds(200, 140, 800, 560);

        pnlUpdateContact.setBackground(new java.awt.Color(255, 153, 153));
        pnlUpdateContact.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlUpdateContact.setLayout(null);

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("UPDATE THE CONTACT");
        pnlUpdateContact.add(jLabel33);
        jLabel33.setBounds(200, 20, 440, 40);

        jLabel34.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Enter The Email-ID :");
        pnlUpdateContact.add(jLabel34);
        jLabel34.setBounds(430, 180, 200, 20);

        jLabel35.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Enter The Name :");
        pnlUpdateContact.add(jLabel35);
        jLabel35.setBounds(80, 100, 170, 20);

        cmbUname.setBackground(new java.awt.Color(255, 153, 153));
        cmbUname.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        cmbUname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select The Phone-No" }));
        cmbUname.setToolTipText("");
        cmbUname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cmbUname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbUnameItemStateChanged(evt);
            }
        });
        cmbUname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUnameActionPerformed(evt);
            }
        });
        pnlUpdateContact.add(cmbUname);
        cmbUname.setBounds(140, 130, 230, 30);

        txtUaddress.setBackground(new java.awt.Color(255, 153, 153));
        txtUaddress.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtUaddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnlUpdateContact.add(txtUaddress);
        txtUaddress.setBounds(140, 210, 240, 30);

        txtUphone.setBackground(new java.awt.Color(255, 153, 153));
        txtUphone.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtUphone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtUphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUphoneActionPerformed(evt);
            }
        });
        pnlUpdateContact.add(txtUphone);
        txtUphone.setBounds(500, 120, 240, 30);

        txtUage.setBackground(new java.awt.Color(255, 153, 153));
        txtUage.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtUage.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtUage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUageActionPerformed(evt);
            }
        });
        pnlUpdateContact.add(txtUage);
        txtUage.setBounds(500, 370, 70, 30);

        jLabel36.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Enter The Phone-No :");
        pnlUpdateContact.add(jLabel36);
        jLabel36.setBounds(430, 80, 200, 40);

        jLabel37.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText(" Age :");
        pnlUpdateContact.add(jLabel37);
        jLabel37.setBounds(430, 360, 70, 30);

        txtUemailid.setBackground(new java.awt.Color(255, 153, 153));
        txtUemailid.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtUemailid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnlUpdateContact.add(txtUemailid);
        txtUemailid.setBounds(490, 210, 250, 30);

        jLabel38.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Enter The Address :");
        pnlUpdateContact.add(jLabel38);
        jLabel38.setBounds(100, 180, 158, 21);

        jLabel39.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Enter The Pin Code :");
        pnlUpdateContact.add(jLabel39);
        jLabel39.setBounds(90, 340, 190, 21);

        txtUzipcode.setBackground(new java.awt.Color(255, 153, 153));
        txtUzipcode.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtUzipcode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnlUpdateContact.add(txtUzipcode);
        txtUzipcode.setBounds(210, 370, 90, 23);

        jLabel40.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Enter The State :");
        pnlUpdateContact.add(jLabel40);
        jLabel40.setBounds(80, 260, 170, 21);

        txtUstate.setBackground(new java.awt.Color(255, 153, 153));
        txtUstate.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtUstate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtUstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUstateActionPerformed(evt);
            }
        });
        pnlUpdateContact.add(txtUstate);
        txtUstate.setBounds(140, 290, 240, 30);

        cmbudate.setBackground(new java.awt.Color(255, 153, 153));
        cmbudate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbudate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "01", "02", "03", "04", "05", "06", "07", "08", "09", "19", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        pnlUpdateContact.add(cmbudate);
        cmbudate.setBounds(490, 290, 60, 30);

        cmbumonth.setBackground(new java.awt.Color(255, 153, 153));
        cmbumonth.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbumonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        pnlUpdateContact.add(cmbumonth);
        cmbumonth.setBounds(560, 290, 70, 30);

        cmbuyear.setBackground(new java.awt.Color(255, 153, 153));
        cmbuyear.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbuyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", " " }));
        pnlUpdateContact.add(cmbuyear);
        cmbuyear.setBounds(640, 290, 90, 30);

        jLabel41.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("  Date of Birth:");
        pnlUpdateContact.add(jLabel41);
        jLabel41.setBounds(430, 260, 140, 30);

        jLabel42.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Select The Gender :");
        pnlUpdateContact.add(jLabel42);
        jLabel42.setBounds(90, 420, 190, 20);

        jRadioButton3.setBackground(new java.awt.Color(255, 153, 153));
        buttonGroup3.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jRadioButton3.setText("Female");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        pnlUpdateContact.add(jRadioButton3);
        jRadioButton3.setBounds(260, 450, 93, 30);

        jRadioButton4.setBackground(new java.awt.Color(255, 153, 153));
        buttonGroup3.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jRadioButton4.setText("Male");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        pnlUpdateContact.add(jRadioButton4);
        jRadioButton4.setBounds(160, 450, 65, 29);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("CANCEL");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        pnlUpdateContact.add(jButton7);
        jButton7.setBounds(460, 500, 120, 30);

        btnupdate.setBackground(new java.awt.Color(0, 0, 0));
        btnupdate.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        pnlUpdateContact.add(btnupdate);
        btnupdate.setBounds(260, 500, 130, 30);

        getContentPane().add(pnlUpdateContact);
        pnlUpdateContact.setBounds(200, 140, 800, 560);

        DeleteContact.setBackground(new java.awt.Color(255, 153, 153));
        DeleteContact.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        DeleteContact.setLayout(null);

        jLabel49.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel49.setText("DELETE THE CONTACT");
        DeleteContact.add(jLabel49);
        jLabel49.setBounds(230, 80, 410, 40);

        jLabel50.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel50.setText(" Phone No :-");
        DeleteContact.add(jLabel50);
        jLabel50.setBounds(230, 300, 101, 30);

        txtDphone.setBackground(new java.awt.Color(255, 153, 153));
        txtDphone.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtDphone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        DeleteContact.add(txtDphone);
        txtDphone.setBounds(340, 300, 240, 30);

        jLabel51.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel51.setText("Name :- ");
        DeleteContact.add(jLabel51);
        jLabel51.setBounds(240, 220, 70, 30);

        btncancel.setBackground(new java.awt.Color(0, 0, 0));
        btncancel.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("CANCEL");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        DeleteContact.add(btncancel);
        btncancel.setBounds(440, 400, 113, 29);

        btndelete.setBackground(new java.awt.Color(0, 0, 0));
        btndelete.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        DeleteContact.add(btndelete);
        btndelete.setBounds(290, 400, 110, 29);

        cmbDname.setBackground(new java.awt.Color(255, 153, 153));
        cmbDname.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        cmbDname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select The Name" }));
        cmbDname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cmbDname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDnameItemStateChanged(evt);
            }
        });
        cmbDname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbDnameMouseClicked(evt);
            }
        });
        cmbDname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDnameActionPerformed(evt);
            }
        });
        DeleteContact.add(cmbDname);
        cmbDname.setBounds(330, 220, 240, 30);

        getContentPane().add(DeleteContact);
        DeleteContact.setBounds(200, 140, 800, 560);

        ViewContact.setBackground(new java.awt.Color(255, 153, 153));
        ViewContact.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        ViewContact.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("VIEW CONTACT ");
        ViewContact.add(jLabel16);
        jLabel16.setBounds(310, 10, 320, 40);

        jLabel17.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText(" Email-ID :");
        ViewContact.add(jLabel17);
        jLabel17.setBounds(500, 180, 110, 20);

        jLabel18.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText(" Name :");
        ViewContact.add(jLabel18);
        jLabel18.setBounds(240, 100, 80, 30);

        txtVaddress.setBackground(new java.awt.Color(255, 153, 153));
        txtVaddress.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtVaddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        ViewContact.add(txtVaddress);
        txtVaddress.setBounds(270, 200, 220, 30);

        txtVphone.setBackground(new java.awt.Color(255, 153, 153));
        txtVphone.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtVphone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        ViewContact.add(txtVphone);
        txtVphone.setBounds(530, 120, 220, 30);

        txtVage.setBackground(new java.awt.Color(255, 153, 153));
        txtVage.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtVage.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtVage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVageActionPerformed(evt);
            }
        });
        ViewContact.add(txtVage);
        txtVage.setBounds(580, 360, 70, 30);

        jLabel19.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText(" Phone-No :");
        ViewContact.add(jLabel19);
        jLabel19.setBounds(490, 100, 130, 20);

        jLabel20.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText(" Age :");
        ViewContact.add(jLabel20);
        jLabel20.setBounds(520, 360, 50, 30);

        txtvemailid.setBackground(new java.awt.Color(255, 153, 153));
        txtvemailid.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtvemailid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        ViewContact.add(txtvemailid);
        txtvemailid.setBounds(530, 200, 220, 30);

        jLabel21.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText(" Address :");
        ViewContact.add(jLabel21);
        jLabel21.setBounds(240, 170, 100, 30);

        jLabel22.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText(" Pin Code :");
        ViewContact.add(jLabel22);
        jLabel22.setBounds(260, 330, 90, 21);

        txtVzipcode.setBackground(new java.awt.Color(255, 153, 153));
        txtVzipcode.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtVzipcode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        ViewContact.add(txtVzipcode);
        txtVzipcode.setBounds(310, 350, 90, 30);

        jLabel23.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("State :");
        ViewContact.add(jLabel23);
        jLabel23.setBounds(250, 260, 80, 21);

        txtVstate.setBackground(new java.awt.Color(255, 153, 153));
        txtVstate.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtVstate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        ViewContact.add(txtVstate);
        txtVstate.setBounds(270, 280, 220, 30);

        cmbvdate.setBackground(new java.awt.Color(255, 153, 153));
        cmbvdate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbvdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "01", "02", "03", "04", "05", "06", "07", "08", "09", "19", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cmbvdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbvdateActionPerformed(evt);
            }
        });
        ViewContact.add(cmbvdate);
        cmbvdate.setBounds(540, 300, 60, 30);

        cmbvmonth.setBackground(new java.awt.Color(255, 153, 153));
        cmbvmonth.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbvmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        ViewContact.add(cmbvmonth);
        cmbvmonth.setBounds(610, 300, 60, 30);

        cmbvyear.setBackground(new java.awt.Color(255, 153, 153));
        cmbvyear.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbvyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        ViewContact.add(cmbvyear);
        cmbvyear.setBounds(680, 300, 80, 30);

        jLabel53.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("  Date of Birth :");
        ViewContact.add(jLabel53);
        jLabel53.setBounds(510, 250, 120, 30);

        jLabel54.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText(" Gender :");
        ViewContact.add(jLabel54);
        jLabel54.setBounds(250, 410, 90, 20);

        rdvfemale.setBackground(new java.awt.Color(255, 153, 153));
        buttonGroup2.add(rdvfemale);
        rdvfemale.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        rdvfemale.setText("Female");
        rdvfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdvfemaleActionPerformed(evt);
            }
        });
        ViewContact.add(rdvfemale);
        rdvfemale.setBounds(380, 440, 93, 30);

        rdVmale.setBackground(new java.awt.Color(255, 153, 153));
        buttonGroup2.add(rdVmale);
        rdVmale.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        rdVmale.setText("Male");
        rdVmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdVmaleActionPerformed(evt);
            }
        });
        ViewContact.add(rdVmale);
        rdVmale.setBounds(290, 440, 65, 29);

        btnCancel.setBackground(new java.awt.Color(0, 0, 0));
        btnCancel.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        ViewContact.add(btnCancel);
        btnCancel.setBounds(440, 500, 120, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("yyyy");
        ViewContact.add(jLabel25);
        jLabel25.setBounds(700, 280, 40, 20);

        jLabel44.setFont(new java.awt.Font("DejaVu Sans Light", 0, 14)); // NOI18N
        jLabel44.setText("Search -");
        ViewContact.add(jLabel44);
        jLabel44.setBounds(20, 120, 60, 17);

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("dd");
        ViewContact.add(jLabel47);
        jLabel47.setBounds(560, 280, 20, 20);

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("mm");
        ViewContact.add(jLabel52);
        jLabel52.setBounds(630, 280, 30, 20);

        cmbsearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbsearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select group", "Family", "Friends", "Workers\t", "Office", "Others" }));
        cmbsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbsearchActionPerformed(evt);
            }
        });
        ViewContact.add(cmbsearch);
        cmbsearch.setBounds(80, 110, 119, 30);

        txtVName1.setBackground(new java.awt.Color(255, 153, 153));
        txtVName1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtVName1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        ViewContact.add(txtVName1);
        txtVName1.setBounds(270, 120, 220, 30);

        tblMame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ));
        tblMame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMameMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMame);

        ViewContact.add(jScrollPane2);
        jScrollPane2.setBounds(20, 160, 200, 350);

        getContentPane().add(ViewContact);
        ViewContact.setBounds(200, 140, 800, 560);

        pnlmenubaar.setBackground(new java.awt.Color(153, 153, 153));
        pnlmenubaar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        pnlmenubaar.setLayout(null);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Add Contact");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnlmenubaar.add(jButton3);
        jButton3.setBounds(30, 70, 150, 30);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Update Contact");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        pnlmenubaar.add(jButton5);
        jButton5.setBounds(30, 170, 150, 30);

        jLabel28.setBackground(new java.awt.Color(0, 0, 0));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login_1.png"))); // NOI18N
        pnlmenubaar.add(jLabel28);
        jLabel28.setBounds(70, 20, 50, 50);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Delete Contact");
        jButton6.setName(""); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        pnlmenubaar.add(jButton6);
        jButton6.setBounds(30, 280, 150, 30);

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login_1.png"))); // NOI18N
        pnlmenubaar.add(jLabel30);
        jLabel30.setBounds(70, 230, 50, 50);

        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login_1.png"))); // NOI18N
        pnlmenubaar.add(jLabel48);
        jLabel48.setBounds(70, 340, 50, 50);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("View Contact");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        pnlmenubaar.add(jButton4);
        jButton4.setBounds(30, 390, 150, 30);

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login_1.png"))); // NOI18N
        pnlmenubaar.add(jLabel29);
        jLabel29.setBounds(70, 120, 50, 50);

        txtlogout.setBackground(new java.awt.Color(0, 0, 0));
        txtlogout.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtlogout.setForeground(new java.awt.Color(255, 255, 255));
        txtlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout1_1.png"))); // NOI18N
        txtlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlogoutActionPerformed(evt);
            }
        });
        pnlmenubaar.add(txtlogout);
        txtlogout.setBounds(70, 470, 50, 50);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Exit");
        pnlmenubaar.add(jLabel24);
        jLabel24.setBounds(80, 520, 29, 20);

        getContentPane().add(pnlmenubaar);
        pnlmenubaar.setBounds(0, 140, 200, 560);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel26.setText("Mange And Stord The Contact Information");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(480, 90, 460, 28);

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel43.setText("WELCOME TO ADDRESS BOOK");
        jPanel3.add(jLabel43);
        jLabel43.setBounds(60, 10, 930, 70);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 970, 140);

        setSize(new java.awt.Dimension(966, 737));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtageActionPerformed
        // TODO add your handling code here:
           
    }//GEN-LAST:event_txtageActionPerformed

    private void txtfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfemaleActionPerformed
        // TODO add your handling code here:
        gen = "Female";
    }//GEN-LAST:event_txtfemaleActionPerformed

    private void txtmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaleActionPerformed
        // TODO add your handling code here:
        gen = "Male";
    }//GEN-LAST:event_txtmaleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pnlAddContact.hide();
        pnlUpdateContact.hide();
        DeleteContact.hide();
        ViewContact.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUageActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        pnlAddContact.hide();
        pnlUpdateContact.hide();
        DeleteContact.hide();
        ViewContact.hide();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cmbUnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUnameActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cmbUnameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          
        getContact();
        ViewContact.show();
        pnlAddContact.hide();
        pnlUpdateContact.hide();
        DeleteContact.hide();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
          cmbDname.removeAllItems();
        cmbDname.addItem("Select The Name");
        getContact();
        DeleteContact.show();
        pnlAddContact.hide();
        pnlUpdateContact.hide();
        ViewContact.hide();
        // ViewContact.

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        cmbUname.removeAllItems();
        cmbUname.addItem("Select The Name");
        getContact();
        pnlUpdateContact.show();
        pnlAddContact.hide();
        DeleteContact.hide();
        ViewContact.hide();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        pnlAddContact.show();
        pnlUpdateContact.hide();
        DeleteContact.hide();
        ViewContact.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        pnlAddContact.hide();
        pnlUpdateContact.hide();
        DeleteContact.hide();
        ViewContact.hide();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        //    pnlAddContact.show();

        c.nonSelect("DELETE FROM `addcontact` WHERE `Name`='" + cmbDname.getSelectedItem() + "'");
        JOptionPane.showMessageDialog(null, "Contact Delete Successfully");
        deleteClearComponent();
    }//GEN-LAST:event_btndeleteActionPerformed
    public void deleteClearComponent() {
        cmbDname.setSelectedIndex(0);;
        txtDphone.setText("");

    }
    private void txtVageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVageActionPerformed

    private void rdvfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdvfemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdvfemaleActionPerformed

    private void rdVmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdVmaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdVmaleActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        pnlAddContact.hide();
        pnlUpdateContact.hide();
        DeleteContact.hide();
        ViewContact.hide();;
        viewClearComponent();
    }//GEN-LAST:event_btnCancelActionPerformed

    public void viewClearComponent() {
        
        txtVphone.setText("");
        txtVphone.setText("");
        txtVaddress.setText("");
        txtvemailid.setText("");
        txtVstate.setText("");
        cmbvdate.setSelectedIndex(0);
        cmbvmonth.setSelectedIndex(0);
        cmbvyear.setSelectedIndex(0);
        txtVzipcode.setText("");
        txtVage.setText("");
       
    }
    //Add Validation Code...
    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here: 
        // if(txtUsername.is)
        if(cmbGroup.getSelectedItem().equals("Select The Group"))
        {JOptionPane.showMessageDialog(pnlAddContact, "Plase Select The Group!!!");
        }else if (txtname.getText().toString().isEmpty()) {
            JOptionPane.showMessageDialog(pnlAddContact, "Plase Enter The Name!!!");
        } else if (!validation(txtname.getText())) {
            JOptionPane.showMessageDialog(pnlAddContact, "Plase Enter Valid Name");
        }else if (txtphoneno.getText().toString().isEmpty()) {
            JOptionPane.showMessageDialog(pnlAddContact, "Plase Enter The Phone-No!!!");
        }else if (!txtphoneno.getText().matches("\\d{0}\\d{10}")) {
            JOptionPane.showMessageDialog(pnlAddContact, "Plase Enter The Valid Phone-No!!!");
        } else if (txtAddress.getText().toString().isEmpty()) {
            JOptionPane.showMessageDialog(pnlAddContact, "Plase Enter The Address!!!");
        }else if (!addressvalidation(txtname.getText())) {
            JOptionPane.showMessageDialog(pnlAddContact, "Plase Enter Valid Address");
        } else if (txtemailid.getText().toString().isEmpty()) {
            JOptionPane.showMessageDialog(pnlAddContact, "Plase Enter The Email-ID!!!");
        } else if (!txtemailid.getText().matches("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+(?:\\.[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+)*@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$")) {
            JOptionPane.showMessageDialog(null, "Plase Enter Valid Email !!!");
        }else if (txtstate.getText().toString().isEmpty()) {
            JOptionPane.showMessageDialog(pnlAddContact, "Plase Enter The State!!!");
        } else if (!validation(txtstate.getText())) {
            JOptionPane.showMessageDialog(pnlAddContact, "Plase Enter Valid State Name");
        }else  if (cmbdate.toString().toString().isEmpty()) {
            JOptionPane.showMessageDialog(pnlAddContact, "Plase Select date!!!");
        } else if (cmbmonth.toString().toString().isEmpty()) {
            JOptionPane.showMessageDialog(pnlAddContact, "Plase Select Month!!!");
        } else if (cmbyears.toString().toString().isEmpty()) {
            JOptionPane.showMessageDialog(pnlAddContact, "Plase Select Year!!!");
        } else if (txtzipcode.getText().toString().isEmpty()) {
            JOptionPane.showMessageDialog(pnlAddContact, "Plase Enter The Pin Code!!!");
        }  else if (!txtzipcode.getText().matches("^[1-9][0-9]{5}$")) {
            JOptionPane.showMessageDialog(pnlAddContact, "Plase Enter The Valid Pin Code!!!");
        } else {
            String dob=cmbdate.getSelectedItem()+"/"+cmbmonth.getSelectedItem()+"/"+cmbyears.getSelectedItem();
            c.nonSelect("INSERT INTO `addcontact`(`Name`, `Phone-No`, `Address`, `Emali-Id`, `State`, `DateOfBirth`, `ZipCode`, `Age`, `Gender`, `user_email`, `contactgroup`) VALUES ('" + txtname.getText() + "','" + txtphoneno.getText() + "','" + txtAddress.getText() + "','" + txtemailid.getText() + "','" + txtstate.getText() + "','" + dob + "','" + txtzipcode.getText() + "','" + txtage.getText() + "','" + gen + "','" + user_email + "','" + cmbGroup.getSelectedItem() + "')");
            JOptionPane.showMessageDialog(null, "Contact Added Successfully");
            
          clearComponent();
     } 
    }//GEN-LAST:event_btnaddActionPerformed

 
  
    public void clearComponent() {
        txtname.setText("");
        txtphoneno.setText("");
        txtAddress.setText("");
        txtemailid.setText("");
        txtstate.setText("");
        cmbdate.setSelectedIndex(0);
        cmbmonth.setSelectedIndex(0);
        cmbyears.setSelectedIndex(0);
        txtzipcode.setText("");
        txtstate.setText("");
        txtage.setText("");
        txtname.requestFocus();
   }
    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        if (cmbUname.getSelectedItem().equals("Select The Name")) {
            JOptionPane.showMessageDialog(pnlUpdateContact, "Plase Select The Name!!!");
        }else if (txtUphone.getText().toString().isEmpty()) {
            JOptionPane.showMessageDialog(pnlUpdateContact, "Plase Enter The Name!!!");
          }else 
//            if (!validation(txtuUname.getText())) {
//            JOptionPane.showMessageDialog(pnlUpdateContact, "Plase Enter Valid Name");
//        } else 
         if (txtUaddress.getText().toString().isEmpty()) {
            JOptionPane.showMessageDialog(pnlUpdateContact, "Plase Enter The Address!!!");
        }else    if (!addressvalidation(txtUaddress.getText())) {
            JOptionPane.showMessageDialog(pnlUpdateContact, "Plase Enter Valid Address");
        } else  if (txtUemailid.getText().toString().isEmpty()) {
            JOptionPane.showMessageDialog(pnlUpdateContact, "Plase Enter The Email-ID!!!");
        } else if (!txtUemailid.getText().matches("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+(?:\\.[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+)*@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$")) {
            JOptionPane.showMessageDialog(null, "Plase Enter Valid Email !!!");
        }else if (txtUstate.getText().toString().isEmpty()) {
            JOptionPane.showMessageDialog(pnlUpdateContact, "Plase Enter The State!!!");
        } else  if (!validation(txtname.getText())) {
            JOptionPane.showMessageDialog(pnlAddContact, "Plase Enter Valid state");
        } else if (cmbudate.toString().toString().isEmpty()) {
        }else if (cmbumonth.toString().toString().isEmpty()) {
            JOptionPane.showMessageDialog(pnlUpdateContact, "Plase Select Month!!!");
        } else if (cmbuyear.toString().toString().isEmpty()) {
            JOptionPane.showMessageDialog(pnlUpdateContact, "Plase Select Year!!!");
        } else if (txtUzipcode.getText().toString().isEmpty()) {  
            JOptionPane.showMessageDialog(pnlUpdateContact, "Plase Enter The Zip Code!!!");
        }else if (!txtzipcode.getText().matches("^[1-9][0-9]{5}$")) {
            JOptionPane.showMessageDialog(pnlAddContact, "Plase Enter The Valid Pin Code!!!");
        }                                                                                                                                                                                                                                         
       else{ String dob=cmbdate.getSelectedItem()+"/"+cmbmonth.getSelectedItem()+"/"+cmbyears.getSelectedItem();
            c.nonSelect("UPDATE `addcontact` SET `Name`='" + txtUphone.getText() + "',`Address`='" + txtUaddress.getText() + "',`Emali-Id`='" + txtUemailid.getText() + "',`State`='" + txtUstate.getText() + "',`DateOfBirth`='" + dob + "',`ZipCode`='" + txtUzipcode.getText() + "',`Age`='" + txtUage.getText() + "',`Gender`='" + gen + "' WHERE `Phone-No`='" + cmbUname.getSelectedItem() + "'");
            JOptionPane.showMessageDialog(null, "Contact Updated Successfully!!!");
            updateClearComponent();
        }

    }//GEN-LAST:event_btnupdateActionPerformed
    public void updateClearComponent() {
        
        txtUphone.setText("");
        cmbUname.setSelectedIndex(0);
        txtUaddress.setText("");
        txtUemailid.setText("");
        txtUstate.setText("");
        cmbudate.setSelectedIndex(0);
        cmbumonth.setSelectedIndex(0);
        cmbuyear.setSelectedIndex(0);
        txtUzipcode.setText("");
        txtUage.setText("");
        txtUphone.requestFocus();
    }
    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
           

    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlogoutActionPerformed
        // TODO add your handling code here:

        new Loginpage().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_txtlogoutActionPerformed

    private void cmbDnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDnameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbDnameActionPerformed

    private void cmbDnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbDnameMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_cmbDnameMouseClicked

    private void cmbDnameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDnameItemStateChanged
        // TODO add your handling code here:
        
        try {
             
            c.select("SELECT * FROM `addcontact` WHERE `Name`='" + cmbDname.getSelectedItem().toString() + "'");
            while (c.rs.next()) {
                txtDphone.setText(c.rs.getString("Phone-No"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbDnameItemStateChanged

    private void cmbUnameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbUnameItemStateChanged
        // TODO add your handling code here:
        
         try {
              String dob=cmbdate.getSelectedItem()+"/"+cmbmonth.getSelectedItem()+"/"+cmbyears.getSelectedItem();
            c.select("SELECT * FROM `addcontact` WHERE `Name`='" + cmbUname.getSelectedItem().toString().trim() + "'");
            while (c.rs.next()) {
                txtUphone.setText(c.rs.getString("Phone-No"));
                txtUaddress.setText(c.rs.getString("Address"));
                txtUemailid.setText(c.rs.getString("Emali-Id"));
                txtUstate.setText(c.rs.getString("State"));
               
                txtUzipcode.setText(c.rs.getString("ZipCode"));
                txtUage.setText(c.rs.getString("Age"));
                gen = c.rs.getString("Gender");
                if (gen.equals("Male")) {
                    rdVmale.setSelected(true);
                } else {
                    rdvfemale.setSelected(true);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbUnameItemStateChanged

    private void cmbyearsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbyearsItemStateChanged
        // TODO add your handling code here:
                 String dobs=cmbyears.getSelectedItem()+"-"+cmbmonth.getSelectedItem()+"-"+cmbdate.getSelectedItem();
        
        LocalDate dob = LocalDate.parse(dobs);
                LocalDate currDate = LocalDate.now();
                 		
		Period period = Period.between(currDate, dob);

		int dobYear = Math.abs(period.getYears());
		txtage.setText(""+dobYear);
		System.out.print(dobYear);
        
        
        
        
    }//GEN-LAST:event_cmbyearsItemStateChanged

    private void cmbvdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbvdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbvdateActionPerformed

    private void txtemailidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailidActionPerformed
        // TODO add your handling code here:
            
    }//GEN-LAST:event_txtemailidActionPerformed

    private void cmbdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbdateActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
            
      
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtphonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphonenoActionPerformed
         // TODO add your handling code here:
           
      
    }//GEN-LAST:event_txtphonenoActionPerformed

    private void txtstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstateActionPerformed

    private void txtzipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtzipcodeActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_txtzipcodeActionPerformed

    private void txtUphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUphoneActionPerformed

    private void txtUstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUstateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUstateActionPerformed

    private void cmbGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGroupActionPerformed

    private void cmbsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbsearchActionPerformed
        // TODO add your handling code here:
              DefaultTableModel data = (DefaultTableModel) tblMame.getModel();
              
              for (int i = data.getRowCount()-1; i>=0;i--){
                  data.removeRow(i);
              }
        try {
            c.select("SELECT `Name` FROM `addcontact` WHERE `contactgroup`='" + cmbsearch.getSelectedItem().toString().trim() + "' AND `user_email`= '" + user_email.trim() + "'");
            while (c.rs.next()) {                
                Object[] row = {c.rs.getString("Name")};
                data.addRow(row);
                
            }            
        } catch (SQLException ex) {
            Logger.getLogger(frmDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbsearchActionPerformed

    private void tblMameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMameMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) tblMame.getModel();
        int i = tblMame.getSelectedRow();
        
         try {
            c.select("SELECT * FROM `addcontact` WHERE `Name`='" + model.getValueAt(i, 0).toString().trim() + "'");

           while (c.rs.next()) {
                txtVName1.setText(c.rs.getString("Name"));
                txtVphone.setText(c.rs.getString("Phone-No"));
               txtVaddress.setText(c.rs.getString("Address"));
                txtvemailid.setText(c.rs.getString("Emali-Id"));
                txtVstate.setText(c.rs.getString("State"));
                cmbvmonth.setSelectedItem(c.rs.getString("DateOfBirth"));
                cmbvyear.setSelectedItem(c.rs.getString("DateOfBirth"));
                txtVzipcode.setText(c.rs.getString("ZipCode"));
                txtVage.setText(c.rs.getString("Age"));
                gen = c.rs.getString("Gender");
                if (gen.equals("Male")) {
                    rdVmale.setSelected(true);
               } else {
                   rdvfemale.setSelected(true);
               }

            }

       } catch (SQLException ex) {
          Logger.getLogger(frmDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_tblMameMouseClicked

    private void cmbyearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbyearsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbyearsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //  new frmDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DeleteContact;
    private javax.swing.JPanel ViewContact;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cmbDname;
    private javax.swing.JComboBox<String> cmbGroup;
    private javax.swing.JComboBox<String> cmbUname;
    private javax.swing.JComboBox<String> cmbdate;
    private javax.swing.JComboBox<String> cmbmonth;
    private javax.swing.JComboBox<String> cmbsearch;
    private javax.swing.JComboBox<String> cmbudate;
    private javax.swing.JComboBox<String> cmbumonth;
    private javax.swing.JComboBox<String> cmbuyear;
    private javax.swing.JComboBox<String> cmbvdate;
    private javax.swing.JComboBox<String> cmbvmonth;
    private javax.swing.JComboBox<String> cmbvyear;
    private javax.swing.JComboBox<String> cmbyears;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel pnlAddContact;
    private javax.swing.JPanel pnlUpdateContact;
    private javax.swing.JPanel pnlmenubaar;
    private javax.swing.JRadioButton rdVmale;
    private javax.swing.JRadioButton rdvfemale;
    private javax.swing.JTable tblMame;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDphone;
    private javax.swing.JTextField txtUaddress;
    private javax.swing.JTextField txtUage;
    private javax.swing.JTextField txtUemailid;
    private javax.swing.JTextField txtUphone;
    private javax.swing.JTextField txtUstate;
    private javax.swing.JTextField txtUzipcode;
    private javax.swing.JTextField txtVName1;
    private javax.swing.JTextField txtVaddress;
    private javax.swing.JTextField txtVage;
    private javax.swing.JTextField txtVphone;
    private javax.swing.JTextField txtVstate;
    private javax.swing.JTextField txtVzipcode;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtemailid;
    private javax.swing.JRadioButton txtfemale;
    private javax.swing.JButton txtlogout;
    private javax.swing.JRadioButton txtmale;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphoneno;
    private javax.swing.JTextField txtstate;
    private javax.swing.JTextField txtvemailid;
    private javax.swing.JTextField txtzipcode;
    // End of variables declaration//GEN-END:variables
}
