
import com.placeholder.PlaceHolder;
import java.time.LocalDate;
import java.time.Period;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mosin
 */
public class ragistarpage extends javax.swing.JFrame {

    /**
     * Creates new form ragistarpage
     */
        DBConn c =new DBConn();
        
      
    public ragistarpage() {
        initComponents();
        
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        register = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtRemail = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        register.setBackground(new java.awt.Color(0, 0, 0));
        register.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTER");
        register.add(jLabel1);
        jLabel1.setBounds(200, 10, 210, 50);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password :");
        register.add(jLabel2);
        jLabel2.setBounds(100, 380, 110, 30);

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FullName :");
        register.add(jLabel3);
        jLabel3.setBounds(100, 120, 110, 40);

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("UserName :");
        register.add(jLabel4);
        jLabel4.setBounds(100, 200, 120, 40);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Please fill in this form to create an your account!!");
        register.add(jLabel8);
        jLabel8.setBounds(130, 60, 370, 30);

        txtRemail.setBackground(new java.awt.Color(0, 0, 0));
        txtRemail.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtRemail.setForeground(new java.awt.Color(255, 255, 255));
        txtRemail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtRemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRemailActionPerformed(evt);
            }
        });
        register.add(txtRemail);
        txtRemail.setBounds(200, 330, 210, 30);

        txtFullName.setBackground(new java.awt.Color(0, 0, 0));
        txtFullName.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtFullName.setForeground(new java.awt.Color(255, 255, 255));
        txtFullName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        register.add(txtFullName);
        txtFullName.setBounds(200, 160, 210, 30);

        txtUserName.setBackground(new java.awt.Color(0, 0, 0));
        txtUserName.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(255, 255, 255));
        txtUserName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        register.add(txtUserName);
        txtUserName.setBounds(200, 240, 210, 30);

        txtPassword.setBackground(new java.awt.Color(0, 0, 0));
        txtPassword.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        register.add(txtPassword);
        txtPassword.setBounds(200, 420, 170, 23);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        register.add(jButton1);
        jButton1.setBounds(320, 500, 115, 29);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jButton2.setText("REGISTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        register.add(jButton2);
        jButton2.setBounds(140, 500, 133, 30);

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email-ID :");
        register.add(jLabel7);
        jLabel7.setBounds(100, 290, 100, 40);

        getContentPane().add(register);
        register.setBounds(0, 0, 600, 600);

        setSize(new java.awt.Dimension(613, 595));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
//     c.nonSelect("INSERT INTO `registerinfo`(`FullName`, `Username`, `Email-Id`, `Password`) VALUES ('"+txtFullName.getText()+"','"+txtUserName.getText()+"','"+txtEmail.getText()+"','"+txtPassword.getText()+"')");
        if (txtFullName.getText().toString().isEmpty()) {
            JOptionPane.showMessageDialog(register, "Plase Enter Full Name!!!");
        } else if (txtUserName.getText().toString().isEmpty()) {
            JOptionPane.showMessageDialog(register, "Plase Enter Username!!!");
        } else if (txtRemail.getText().toString().isEmpty()) {
            JOptionPane.showMessageDialog(register, "Plase Enter Email ID!!!");
        }else if (!txtRemail.getText().matches("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+(?:\\.[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+)*@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$")) {
            JOptionPane.showMessageDialog(register, "Plase Enter Valid Email !!!");
        } else if (txtPassword.getText().toString().isEmpty()) {
            JOptionPane.showMessageDialog(register, "Plase Enter Password!!!");
        } else {
            c.nonSelect("INSERT INTO `registerinfo`(`FullName`, `Username`, `Email-Id`, `Password`) VALUES ('" + txtFullName.getText() + "','" + txtUserName.getText() + "','" + txtRemail.getText() + "','" + txtPassword.getText() + "')");
            JOptionPane.showMessageDialog(null, " Successfully Registration...");
            clearComponent();
            new Loginpage().show();
            this.hide();
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void clearComponent() {
        txtFullName.setText("");
        txtUserName.setText("");
        txtRemail.setText("");
        txtPassword.setText("");
        txtFullName.requestFocus();
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Loginpage().show();
        this.hide();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtRemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRemailActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtRemailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ragistarpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ragistarpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ragistarpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ragistarpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ragistarpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel register;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtRemail;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
